### ISSUE TITLE
What 's the difference between "lapsed" and "flunked"?

### ISSUE THREAD

**Issue by purequant** [lovac42/PretzelLogic#4]
This add-on is very useful ,Thanks for your hard work.
But I'm bewildered by the two parameters "Lapsed" and "flunked".

What's the different?

**Comment by lovac42** [comment]
"Flunked" are for review cards that you failed.
"Lapsed cards" is a count of the total relearning cards you've studied today, cards with learning steps.

**Comment by purequant** [comment]
Thanks
